CREATE OR REPLACE VIEW v_sale_sgb_81124 AS
SELECT "SALENO","XSFDM","XSFMC","CGFDM","CGFMC","CPDM","CPMC","CPGG","DW","PH","SL","DJ","JE","CJSJ","销售类型","库位","有效日期","SYZ","YXQ","BILLNO" FROM v_sale_sgb_81124@Hydee_Zy;

CREATE OR REPLACE VIEW V_ACCEPT_sgb_81124 AS
SELECT "XSFMC","CGFDM","CGFMC","CPDM","CPMC","CPGG","PH","SL","DW","DJ","JE","CJSJ","BILLCODE","DISTNO" FROM V_ACCEPT_sgb_81124@HYDEE_ZY;

CREATE OR REPLACE VIEW V_KC_sgb_81124 AS
SELECT "KCRQ","GSDM","GSMC","CPDM","CPMC","CPGG","PH","SL","DJ","JE","DW","CJSJ" FROM V_KC_sgb_81124@HYDEE_ZY;

