INSERT INTO D_YB_NEW_CUS_2024_04
(ERPSALENO, RECEIPTDATE, BUSNO, SALER, USERNAME, CUSTOMERNAME, IDENTITYNO, NB_FLAG, CBD, CBDNAME, NETSUM, STATUS,
 YG_FLAG, JSLX, ORDERNO)
SELECT ERPSALENO, RECEIPTDATE, BUSNO, SALER, USERNAME, CUSTOMERNAME, IDENTITYNO, NB_FLAG, CBD, CBDNAME, NETSUM, STATUS,
       YG_FLAG,
       JSLX, ORDERNO
FROM (SELECT A.ERPSALENO, A.RECEIPTDATE, A.BUSNO, A.SALER, A.USERNAME, A.CUSTOMERNAME, A.IDENTITYNO, A.NB_FLAG, A.CBD,
             A.CBDNAME,
             A.NETSUM, A.STATUS, A.YG_FLAG, A.JSLX,
             A.ORDERNO, A.CBRYLB,
             ROW_NUMBER() OVER (PARTITION BY
                 CASE
                     WHEN a.NB_FLAG=0 and TB2.CLASSCODE IN ('324331001', '324331002','324331003','324331004') THEN '324331001'
                     WHEN a.NB_FLAG=1 and TB2.CLASSCODE IN ('324331001', '324331002') THEN '324331002'
                     ELSE TB2.CLASSCODE
                     END,
                 TB22.CLASSCODE,
                 A.IDENTITYNO,A.NB_FLAG ORDER BY A.RECEIPTDATE ASC) RN
FROM D_YB_FIRST_CUS A
         JOIN T_BUSNO_CLASS_SET TS ON A.BUSNO = TS.BUSNO AND TS.CLASSGROUPNO = '303'
         JOIN T_BUSNO_CLASS_BASE TB ON TS.CLASSGROUPNO = TS.CLASSGROUPNO AND TS.CLASSCODE = TB.CLASSCODE
    AND TB.CLASSCODE IN ('303100', '303101', '303102')
         JOIN T_BUSNO_CLASS_SET TS2 ON A.BUSNO = TS2.BUSNO AND TS2.CLASSGROUPNO = '324'
         JOIN T_BUSNO_CLASS_BASE TB2 ON TS2.CLASSGROUPNO = TS2.CLASSGROUPNO AND TS2.CLASSCODE = TB2.CLASSCODE
         JOIN T_BUSNO_CLASS_SET TS22 ON A.BUSNO = TS22.BUSNO AND TS22.CLASSGROUPNO = '305'
         JOIN T_BUSNO_CLASS_BASE TB22 ON TS22.CLASSGROUPNO = TS22.CLASSGROUPNO AND TS22.CLASSCODE = TB22.CLASSCODE
--加上国谈条件
WHERE A.RECEIPTDATE >= DATE'2024-01-01'
  AND A.CBD IN
      ('331082', '331004', '331083', '331024', '331081', '331023', '331022', '331003', '331002', '331099', '331001')
  --国谈条件
  AND EXISTS(SELECT 1
FROM (SELECT A.SALENO
FROM V_YB_SPXX_DETAIL A
         JOIN T_BUSNO_CLASS_SET TS ON A.BUSNO = TS.BUSNO AND TS.CLASSGROUPNO = '305'
         JOIN T_BUSNO_CLASS_BASE TB ON TS.CLASSGROUPNO = TB.CLASSGROUPNO AND TS.CLASSCODE = TB.CLASSCODE
WHERE TB.CLASSCODE = '30510'
  AND NVL(统筹支付数, 0) + NVL(个人当年帐户支付数, 0) + NVL(公补基金支付数, 0) <> 0
  AND NOT EXISTS(SELECT 1 FROM T_SALE_RETURN_H T1 WHERE T1.SALENO = A.SALENO)
  AND NOT EXISTS(SELECT 1 FROM T_SALE_RETURN_H T2 WHERE T2.RETSALENO = A.SALENO)
  AND NOT EXISTS(SELECT 1
FROM D_LL_GTML GT
WHERE GT.WAREID = A.WAREID
  AND A.ACCDATE BETWEEN GT.BEGINDATE AND GT.ENDDATE
  AND GT.PZFL IN ('双通道品种', '国谈品种'))
UNION ALL
SELECT A.SALENO
FROM V_YB_SPXX_DETAIL A
         JOIN T_BUSNO_CLASS_SET TS ON A.BUSNO = TS.BUSNO AND TS.CLASSGROUPNO = '305'
         JOIN T_BUSNO_CLASS_BASE TB ON TS.CLASSGROUPNO = TB.CLASSGROUPNO AND TS.CLASSCODE = TB.CLASSCODE
WHERE TB.CLASSCODE = '30511'
  AND NVL(统筹支付数, 0) + NVL(个人当年帐户支付数, 0) + NVL(公补基金支付数, 0) <> 0
  AND NOT EXISTS(SELECT 1 FROM T_SALE_RETURN_H T1 WHERE T1.SALENO = A.SALENO)
  AND NOT EXISTS(SELECT 1 FROM T_SALE_RETURN_H T2 WHERE T2.RETSALENO = A.SALENO)
  AND NOT EXISTS(SELECT 1
FROM D_LL_GTML GT
WHERE GT.WAREID = A.WAREID
  AND A.ACCDATE BETWEEN GT.BEGINDATE AND GT.ENDDATE
  AND GT.PZFL IN ('国谈品种'))) aaa where aaa.SALENO=a.ERPSALENO  ))
WHERE RN = 1 and receiptdate>= DATE'2024-04-01' and receiptdate<trunc(sysdate);


select trunc(RECEIPTDATE),count(*) from D_YB_NEW_CUS_2024_04 where RECEIPTDATE>=date'2024-03-01'
group by trunc(RECEIPTDATE);
select ACCDATE,count(*) from V_YB_SPXX_DETAIL
                        where ACCDATE>=date'2024-03-18' group by ACCDATE;

select ACCDATE,count(*)  from D_YBZD_detail where ACCDATE>=date'2024-03-18' group by ACCDATE ;

select trunc(销售日期),count(*) from D_ZHYB_HZ_CYB where 销售日期 >=date'2024-03-18' group by trunc(销售日期);
select trunc(销售日期),count(*)  from v_zhybjsjlb_c  where 销售日期 >=date'2024-04-18' group by trunc(销售日期);